# This is a basic workflow to help you get started with Actions

name: Git Status

# Controls when the workflow will run
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: "Git Commit"
        run: |
          pwd
          ls -al
          txt=$(date +"%Y-%m-%d %H:%M.%S")
          echo $txt
          echo $txt  >> date.txt
          git status
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily Commit [BOT]
